-
  branches:
    only:
      - master
  skip_tags: true
  version: 4.1.0
  
  assembly_info:
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    file: AssemblyInfo.*
    patch: true
   
  os: Visual Studio 2017
  
  install:
    - ps: .\install.ps1
  
  before_build:
    - ps : .\build-before_build.ps1
  
  build:
    verbosity: minimal
    parallel: true
    publish_nuget: true
   
  configuration: Release
  cache:
    - src\packages -> **\packages.config
  
  services:
    - mongodb
  
  test:
    assemblies:
      - '**\*.Tests.dll'
      - '**\*.FunctionalTests.dll'
    categories:
      except:
        - Credstash

  artifacts:
    - path: '*.nupkg'
  
  on_finish:
    - ps : .\build-on_finish.ps1   
  
  deploy:
    - provider: Environment
      name: NuGet.org
      on:
        branch: master
    
    - provider: Environment
      name: GitHub
      on:
        branch: master

-
  skip_tags: true
  version: 4.1.0-{branch}{build}
  
  assembly_info:
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    file: AssemblyInfo.*
    patch: true
   
  os: Visual Studio 2017
  
  install:
    - ps: .\install.ps1
  
  before_build:
    - ps : .\build-before_build.ps1
  
  build:
    verbosity: minimal
    parallel: true
    publish_nuget: true
   
  configuration: Release
  cache:
    - src\packages -> **\packages.config
  
  services:
    - mongodb
  
  test:
    assemblies:
      - '**\*.Tests.dll'
      - '**\*.FunctionalTests.dll'
    categories:
      except:
        - Credstash

  artifacts:
    - path: '*.nupkg'
  
  on_finish:
    - ps : .\build-on_finish.ps1